apiVersion: v1
kind: Service
metadata:
  name: tomcat-srv
spec:
  selector:
    app: tomcat
  ports:
  - name: default
    protocol: TCP
    # service自身的监听端口
    port: 8080
    # 容器应用监听的端口
    target: 8080